### ISSUE TITLE
[Issue] <Add a short description>

### ISSUE THREAD

**Issue by NordicGamerFE** [Valandur/admin-panel#24] opened 2019-07-26 20:40 UTC
<Say a little about what happened>

TypeError: Cannot set property 'editorRef' of undefined

Stacktrace:
    in div
    in t
    in div
    in t
    in div
    in p
    in div
    in t
    in c
    in div
    in t
    in c
    in t
    in t
    in t
    in t
    in Unknown
    in Connect(Component)
    in n
    in t
    in t
    in div
    in p
    in div
    in p
    in div
    in t
    in Unknown
    in Connect(Component)
    in t
    in t
    in t
    in t
    in t
    in t

**Comment by vb-03** [comment] 2019-08-10 00:43
Same bug happening to me when clicking on configs button in plugins

**Comment by vb-03** [comment] 2019-08-10 00:43
Sane as #22 #25

**Comment by Valandur** [comment] 2019-08-10 01:03
Duplicate of #21

**Closed by Valandur** 2019-08-10 01:03 UTC
