### ISSUE TITLE
[Issue] Tried to edit configs inside of the panel for spongeforge

### ISSUE THREAD

**Issue by Piehthyte** [Valandur/admin-panel#22] opened 2019-05-21 17:11 UTC
<Say a little about what happened>

TypeError: Cannot set property 'editorRef' of undefined

Stacktrace:
    in div
    in t
    in div
    in t
    in div
    in p
    in div
    in t
    in c
    in div
    in t
    in c
    in t
    in t
    in t
    in t
    in Unknown
    in Connect(Component)
    in n
    in t
    in t
    in div
    in p
    in div
    in p
    in div
    in t
    in Unknown
    in Connect(Component)
    in t
    in t
    in t
    in t
    in t
    in t

**Comment by Valandur** [comment] 2019-08-10 01:03
Duplicate of #21

**Closed by Valandur** 2019-08-10 01:03 UTC
Labels: duplicate
