### ISSUE TITLE
Can not get all player statistics through the API.

### ISSUE THREAD

**Issue by yaroslav4167** [Valandur/admin-panel#18] opened 2018-05-27 17:52 UTC
I do not get full statistics about the player.
When I try to query: /api/v5/player/{UUID}, I do not receive all statistics about the player (I need the "statistics" item)
And an [error](http://bit.ly/2IVnC3Z) is output to the console.

I used git-version plugin. But, the error was in 5.1.1.
Sponge: 1.12.2-2703-7.1.0-BETA-3116

**Comment by Valandur** [comment] 2018-05-28 09:34
Thanks for the report. Do you have any mods on your server, if yes which ones and what version?

**Comment by yaroslav4167** [comment] 2018-05-28 10:16
Mods&Plugins:
[server](http://bit.ly/2KYOr8k)

**Comment by Valandur** [comment] 2018-05-29 08:17
I can't reproduce this with only Forge, Sponge & Web-API, so it's probably because of one of the mods.
Is that a specific modpack you're using, or did you put those together as a custom collection?
Would make it easier for me to test if it was a modpack

**Comment by yaroslav4167** [comment] 2018-05-29 09:56
No. It's my [custom collection](http://bit.ly/2kyI6VW).

**Comment by Valandur** [comment] 2018-05-29 10:37
Hmm, this is a tricky one. So it works for me, but I'm assuming that might be because it's a certain statistic that I don't have yet, because I haven't played that long/used that action yet.
It would be awesome if you could try and see if fetching the player details works for a new player on the server - one that haven't done much yet. If it does, then it's probably a certain statistic that's causing the issue.
Either way, I have a potential fix ready that I will be deploying as soon as I can. But I can't guarantee that it will work because I can't test it.

**Comment by yaroslav4167** [comment] 2018-05-29 11:57
I deleted the [profile file](http://bit.ly/2sfbk0c) and the error disappeared.
And [one more](http://bit.ly/2sgBgst) error at the entrance / exit.

**Comment by Valandur** [comment] 2018-06-02 11:20
Did the second error only show up after you deleted the profile file? Because I believe the second is a Sponge bug

**Comment by Valandur** [comment] 2018-06-02 12:07
I moved the issue to the correct repository, and I'm going to close this one. Please add any further comments to [the new issue](https://github.com/Valandur/Web-API/issues/96)

**Closed by Valandur** 2018-06-02 12:07 UTC
Labels: bug
