### ISSUE TITLE
API Error

### ISSUE THREAD

**Issue by ziceptor** [Valandur/admin-panel#1] opened 2017-11-06 12:41 UTC
forge-1.12.2-14.23.0.2503-universal.jar
spongeforge-1.12.2-2503-7.0.0-BETA-2720.jar
webapi-4.8.1-S7.0.jar

localhost:
map tab: API Error (Internal server error)
players tab: API Error (Internal server error)
https://gist.github.com/ziceptor/f7c419b5a8d9e2eaa2b3d1c5c046144c

**Comment by Valandur** [comment] 2017-11-06 22:26
Confirmed on API 7, this seems to be something related to the statistics data of the player. Might not happen when using Sponge 6.2. Will fix this soon.

Thanks for reporting this :)

**Comment by Valandur** [comment] 2017-11-07 10:28
Fixed in https://github.com/Valandur/Web-API/releases/tag/v4.8.2

**Closed by Valandur** 2017-11-07 10:28 UTC
Labels: bug
